auto-file-renaming=false
allow-overwrite=true
allow-piece-length-change=true
continue=true
disk-cache=64M
enable-mmap=true
file-allocation=falloc
max-concurrent-downloads=5
max-connection-per-server=16
max-tries=3
quiet=true
split=32